# -*- coding: utf-8 -*-
"""Attendance System(Tech Understanding Demo).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDgbv99Li4cjkW6VcHtrb_Nv2T9G79gm
"""

# @title 🏫 CSI WITS Attendance System (Full Simulation)
# @markdown Run this cell to launch the server, database, and UI.

import os
import sqlite3
import datetime
from typing import List

# --- 1. INSTALL DEPENDENCIES ---
# We install FastAPI for logic, Uvicorn for server, and Gradio for the UI
os.system('pip install fastapi uvicorn gradio pandas -q')

import gradio as gr
import pandas as pd

# --- 2. DATABASE CONFIGURATION ---
DB_NAME = "csi_wits_demo.db"

def init_db():
    """Initializes the SQLite database with dummy data."""
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()

    # Tables
    c.execute('DROP TABLE IF EXISTS gate_entry')
    c.execute('DROP TABLE IF EXISTS attendance')
    c.execute('DROP TABLE IF EXISTS students')

    c.execute('''CREATE TABLE students
                 (roll_no TEXT PRIMARY KEY, name TEXT, phone TEXT)''')

    c.execute('''CREATE TABLE gate_entry
                 (roll_no TEXT, timestamp DATETIME)''')

    c.execute('''CREATE TABLE attendance
                 (id INTEGER PRIMARY KEY, roll_no TEXT, status TEXT,
                  timestamp DATETIME, notes TEXT)''')

    # Seed Dummy Students (2nd Year CSE)
    students = [
        ("22XU1A0501", "Amit Sharma", "9900000001"),
        ("22XU1A0502", "Priya Verma", "9900000002"),
        ("22XU1A0503", "Rahul Reddy", "9900000003"),
        ("22XU1A0504", "Sneha Iyer", "9900000004"),
        ("22XU1A0505", "Vikram Singh", "9900000005"),
    ]
    c.executemany("INSERT INTO students VALUES (?,?,?)", students)
    conn.commit()
    conn.close()

# Initialize DB on first run
init_db()

# --- 3. CORE LOGIC (BACKEND) ---

def gate_scan(roll_no):
    """Simulates scanning a QR code at the gate."""
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()

    # Verify student exists
    student = c.execute("SELECT name FROM students WHERE roll_no=?", (roll_no,)).fetchone()
    if not student:
        conn.close()
        return f"❌ Error: Roll Number {roll_no} not found in database."

    # Log Entry
    c.execute("INSERT INTO gate_entry VALUES (?, ?)", (roll_no, datetime.datetime.now()))
    conn.commit()
    conn.close()
    return f"✅ GATE OPEN: Welcome, {student[0]} ({roll_no})"

def submit_class_attendance(selected_students):
    """
    Simulates the Professor App submission.
    logic: Cross-checks selected students against Gate Entry table.
    """
    if not selected_students:
        return "⚠️ No students selected."

    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()

    # Get today's gate entries
    c.execute("SELECT roll_no FROM gate_entry") # In real app, filter by DATE
    gate_entries = {row[0] for row in c.fetchall()}

    # Get all students to find absentees
    all_students = c.execute("SELECT roll_no FROM students").fetchall()
    all_roll_nos = [s[0] for s in all_students]

    logs = []
    sms_alerts = []

    for roll in all_roll_nos:
        # Determine Status
        is_marked_present = roll in selected_students
        has_gate_entry = roll in gate_entries

        final_status = "UNKNOWN"
        note = ""

        if is_marked_present and has_gate_entry:
            final_status = "PRESENT"
            note = "✅ Validated"
        elif is_marked_present and not has_gate_entry:
            final_status = "ABSENT"
            note = "❌ PROXY BLOCKED (No Gate Scan)"
        elif not is_marked_present and has_gate_entry:
            final_status = "ABSENT"
            note = "⚠️ BUNKING (Gate Scan Found)"
            sms_alerts.append(f"SMS to Guardian of {roll}: Your ward is absent.")
        else:
            final_status = "ABSENT"
            note = "Legitimately Absent"

        # Save to DB
        c.execute("INSERT INTO attendance (roll_no, status, timestamp, notes) VALUES (?, ?, ?, ?)",
                  (roll, final_status, datetime.datetime.now(), note))

        logs.append([roll, final_status, note])

    conn.commit()
    conn.close()

    # Format output for UI
    log_text = pd.DataFrame(logs, columns=["Roll No", "Final Status", "System Note"])
    alert_text = "\n".join(sms_alerts) if sms_alerts else "No SMS Alerts Triggered."

    return log_text, alert_text

def view_database():
    """Helper to see raw DB tables"""
    conn = sqlite3.connect(DB_NAME)
    df_gate = pd.read_sql_query("SELECT * FROM gate_entry", conn)
    df_att = pd.read_sql_query("SELECT * FROM attendance ORDER BY id DESC", conn)
    conn.close()
    return df_gate, df_att

# --- 4. GRADIO USER INTERFACE ---

with gr.Blocks(title="CSI WITS Attendance System", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🏫 CSI WITS: Secure Attendance System")
    gr.Markdown("### Designed for Offline-First, Anti-Proxy Validation")

    with gr.Tab("👮 Gate Security (Level 1)"):
        gr.Markdown("Simulate the Physical Gate Scanner here.")
        with gr.Row():
            # Dropdown simulates scanning a QR code
            student_selector = gr.Dropdown(
                choices=["22XU1A0501", "22XU1A0502", "22XU1A0503", "22XU1A0504", "22XU1A0505"],
                label="Scan Student QR Code",
                info="Select a student to simulate them walking through the gate."
            )
            scan_btn = gr.Button("模拟 SCAN QR", variant="primary")
        gate_output = gr.Textbox(label="Gate Device Screen")
        scan_btn.click(gate_scan, inputs=student_selector, outputs=gate_output)

    with gr.Tab("👨‍🏫 Professor App (Level 2)"):
        gr.Markdown("Professor selects students visibly present in class.")

        # Checkbox group simulates the Mobile App List
        class_list = gr.CheckboxGroup(
            choices=["22XU1A0501", "22XU1A0502", "22XU1A0503", "22XU1A0504", "22XU1A0505"],
            label="Mark Attendance (Select visible students)",
            info="Try marking someone who DID NOT scan at the gate to see Proxy Blocking."
        )
        submit_btn = gr.Button("Submit Attendance", variant="primary")

        gr.Markdown("### 📊 System Reconciliation Results")
        result_df = gr.Dataframe(label="Attendance Ledger")
        sms_output = gr.Textbox(label="SMS Notification Log", lines=4)

        submit_btn.click(submit_class_attendance, inputs=class_list, outputs=[result_df, sms_output])

    with gr.Tab("🗄️ Database View"):
        refresh_btn = gr.Button("Refresh Tables")
        with gr.Row():
            gate_table = gr.Dataframe(label="Gate Entry Table")
            att_table = gr.Dataframe(label="Final Attendance Table")
        refresh_btn.click(view_database, outputs=[gate_table, att_table])

# Launch the App
demo.launch(debug=False, height=800)